# Generated by Django 5.1.4 on 2026-05-24 17:48

import ckeditor_uploader.fields
import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to=content.models.path_to_photos_images, verbose_name='Картинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('order', models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['order'],
            },
        ),
    ]
