# Generated by Django 5.1.4 on 2026-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='text',
        ),
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок'),
        ),
    ]
