# Generated by Django 5.1.4 on 2026-05-24 18:05

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_photo_text_alter_photo_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to=content.models.path_to_photos_images, verbose_name='Картинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
                'ordering': ['order'],
            },
        ),
    ]
