# Generated by Django 5.1.4 on 2026-05-24 18:09

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='image',
            field=models.ImageField(blank=True, upload_to=content.models.path_to_layouts_images, verbose_name='Картинка'),
        ),
    ]
