# Generated by Django 5.1.4 on 2026-05-24 18:19

import ckeditor_uploader.fields
import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_layout_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to=content.models.path_to_attraction_images, verbose_name='Картинка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст описание')),
                ('tags', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Теги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
                'ordering': ['order'],
            },
        ),
    ]
