# Generated by Django 5.1.4 on 2026-05-24 18:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст'),
        ),
    ]
