# Generated by Django 5.1.4 on 2026-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_attraction_tags_alter_attraction_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='tags',
            field=models.TextField(blank=True, max_length=500, verbose_name='Теги'),
        ),
    ]
