# Generated by Django 5.1.4 on 2026-05-24 18:41

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_attraction_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('types', models.CharField(choices=[('benefits', 'Идеальное месторасположение'), ('concept', 'Концепция «Город в городе»'), ('secure', 'Безопасность и приватность'), ('offer', 'Лучшее предложение на рынке')], max_length=500, verbose_name='Тип карточки')),
                ('image', models.ImageField(blank=True, upload_to=content.models.path_to_cards_images, verbose_name='Картинка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('svg_icon', models.CharField(blank=True, max_length=500, verbose_name='SVG иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['order'],
            },
        ),
    ]
