# Generated by Django 5.1.4 on 2026-05-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='types',
            new_name='type',
        ),
    ]
