# Generated by Django 5.1.4 on 2026-05-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_types_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='svg_icon',
            field=models.TextField(blank=True, verbose_name='SVG иконка'),
        ),
    ]
