# Generated by Django 5.1.4 on 2026-05-24 20:04

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_card_svg_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('file', models.FileField(blank=True, upload_to=content.models.path_to_documents_files, verbose_name='Файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('order', models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['order'],
            },
        ),
    ]
