# Generated by Django 5.1.4 on 2026-05-24 20:32

import ckeditor_uploader.fields
import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to=content.models.path_to_articles_images, verbose_name='Картинка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('slug', models.SlugField(max_length=500, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-date',),
            },
        ),
    ]
