# Generated by Django 5.1.4 on 2026-05-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя')),
                ('phone', models.CharField(max_length=500, verbose_name='Телефон')),
                ('sub', models.CharField(max_length=500, verbose_name='Тема сообщения')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработанная?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
    ]
