# Generated by Django 5.1.4 on 2026-05-25 06:44

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, upload_to=content.models.path_to_articles_images, verbose_name='Видео-файл'),
        ),
    ]
