# Generated by Django 5.1.4 on 2026-08-12 20:39

import ckeditor_uploader.fields
from django.db import migrations, models


def create_home_seo_block(apps, schema_editor):
    HomeSEOBlock = apps.get_model('content', 'HomeSEOBlock')
    HomeSEOBlock.objects.get_or_create(
        title='Инвестиции в недвижимость в Абхазии',
        defaults={'is_active': True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_article_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSEOBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Инвестиции в недвижимость в Абхазии', help_text='На странице это будет заголовок второго уровня. Не используйте H1 в тексте статьи.', max_length=255, verbose_name='Заголовок статьи (H2)')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Добавьте статью с подзаголовками H3 и обычными абзацами. Пока поле пустое, блок на сайте не показывается.', verbose_name='Текст SEO-статьи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'SEO-статья на главной',
                'verbose_name_plural': 'SEO-статья на главной',
            },
        ),
        migrations.RunPython(create_home_seo_block, migrations.RunPython.noop),
    ]
